Avoid variable that is present only in debug mode
Addressing:
probes/probe-api.c: In function 'probe_obj_attrexists':
probes/probe-api.c:552:9: error: variable 'name_len' set but not used
[-Werror=unused-but-set-variable]
  size_t name_len;
         ^